//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Progra.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public int ID_CARRITO { get; set; }
        public int TOTAL { get; set; }
        public int CANTIDAD { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
