//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Progra.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public short ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public double PRECIO { get; set; }
        public short CANTIDAD { get; set; }
        public short ID_CATEGORIA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
