//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Progra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.CARRITO = new HashSet<CARRITO>();
        }
    
        public int ID_USUARIO { get; set; }
        [StringLength(20, ErrorMessage = "El nombre no debe ser mayor a 20 letras")]
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string CONTRASENA { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        [DisplayName("Direccion de Correo")]
        [StringLength(0, ErrorMessage = "El email no debe ser mayor a  letras")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO> CARRITO { get; set; }
    }
}
